[package]
name = "nfg-timer"
version = "1.0.0"
authors = ["Brian Misiak <bm@net4game.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
samp = "0.1.2"
log = "0.4.6"
fern = "0.5.7"